  
version: "3.3"


services:

  era-db:
    container_name: "era-db"
    image: mysql:latest
    volumes:
      - type: volume
        source: era-volume
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: era

  service1:
    container_name: "service1"
    image: thush3304/service1
    build: ./service1
    environment: 
      DATABASE_URI: 
    restart: on-failure
    deploy:
      replicas: 2
    
  service2:
    container_name: "service2"
    image: thush3304/service2
    build: ./service2
    deploy:
      replicas: 2
  
  service3:
    container_name: "service-3"
    image: thush3304/service3
    build: ./service3
    deploy:
      replicas: 2

  service4:
    container_name: "service4"
    image: thush3304/service4
    build: ./service4
    deploy:
      replicas: 2

  #Era proxy
  era-proxy:
    container_name: era-proxy
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - service1

volumes:
  era-volume: