# tasks file for Install Dockers

- name: Install dependencies
  apt:
    name:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg
      - lsb-release
    update_cache: true


- name: Add apt Key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg



- name: Setup Stable Repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu/ bionic stable
    

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli 
      - containerd.io
      - python3-docker
    update_cache: true