  
- hosts: load-balancer
  become: true
  roles:
    - Configure NGINX
    
- hosts:
    - docker-manager
    - workers
  become: true
  roles:
    - Install Dockers

- hosts: docker-manager
  become: true
  roles: 
    - Initialise Swarm
  
- hosts: workers
  become: true
  roles:
    - Join Swarm